### ISSUE TITLE
Enhance "Contains" functionality to be Contains or Equal

### ISSUE THREAD

**Issue by ppatel2289** [SFDO-Community/Salesforce-Indicators#111]
I created 3 Custom picklists on the Rating with Indicator Item Extensions Label **Rating - Average**, **Rating - Below Average**, and  **Rating - Best**. 
Provided different Image URL for each Label. **Rating - Average** and **Rating - Below Average** was showing the same image even though changing the picklist values. Values were changing but the image were the same. 

![image](https://user-images.githubusercontent.com/99363946/228947463-872cea33-cae7-4dcd-8e12-0a3fc9849185.png)

![image](https://user-images.githubusercontent.com/99363946/228947546-b1f80487-1d1f-4d19-8d8e-d3cc6c725b38.png)

Included priority 1 for Average and 2 for Below; and changed **Rating - Below Average** to **Rating - Below**  under Contains Text for Indicator Item Extension. It resolved the issue.
![image](https://user-images.githubusercontent.com/99363946/228947983-0680e41e-8cf2-47d6-b771-07438883ebd4.png)

May be having the repeat word "Average" is not supported in the Contains text or it just takes one word only!

**Comment by tschug** [comment]
Yes - this is the result of using a "contains" or "includes" logic, all 3 options have the word `Average` and that is why it's not a great search word based on how the component is built today.

Therefore, I am thinking we offer the following options:
1. Case
   - Case-Sensitive
    - Right now we are using the JavaScript includes( ) method [which is case-sensitive](https://www.w3schools.com/jsref/jsref_includes.asp).
      - Most of the methods I list below are case-sensitive.
   - Case-Insensitive
     - The common practice is to just convert the value to all upper or lower (same with the search word)
     - MAYBE we do this by default, unless stated otherwise to "enable" Sensitivity (and Data Type, explained below)
2. Searching
   - Contains/Includes
     - We have this today
   - Starts With
     - I just had an SOQL on an accounting string that started with a specific value
   - Ends With
     - AND it had to end with a specific value.
   - Exact Match - Text
     - We may want to convert anything that looks like a number to a String and then do the comparison.  So 0.00 does not match 0.
     - MAYBE this is where Case-Sensitive comes in
   - Exact Match - Numerical
     - I'm not sure about this one, but I'm thinking if you wanted to say it must be a certain value (and you didn't want a range.
     - Convert the CMDT string to a number.  So 0.00 does match 0.
     - Maybe this is a new "case" for Numerical-Sensitive ?
   - Equals
     - Ignoring data type so the number 5 equals the text 5.
     - Maybe this is where Case-Insensitive comes in?
   - Not Equal
   - Not Equal Value nor Type

**Comment by ppatel2289** [comment]
Thank you Tim for providing detail explanations. I will check this out.

Regards,
Paulomi

Thank you

**Comment by JodieM** [comment]
Just confirming @ppatel2289 these are suggestions we have for enhancing this issue in the future, there is no fix for this issue right now... Tim is just putting it out there as to what we could build in the future.

**Comment by JodieM** [comment]
Fixed in feature/contains-equals. Really nice functionality. Needs documentation.
