### ISSUE TITLE
Github Issue Templates with wrong Assignees

### ISSUE THREAD

**Issue by tschug** [SFDO-Community/Salesforce-Indicators#127]
**Describe the bug**
Github issue templates are assigning wrong individuals.

**To Reproduce**
1. In Github, create a new issue as a Bug or Feature Request
2. Observe that `rdblake21` is being assigned the issue.

**Expected behavior**
No auto-assignees at this time.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
David Reed confirmed and gave us the okay to update.

**Comment by JodieM** [comment]
Also the Enhancement Template refers to the Summit Events App
