### ISSUE TITLE
Asterisk in Indicator Item Extension does not display the Icon

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community/Salesforce-Indicators#130]
**Describe the bug**
When using "*" in the Indicator Item Extension Contains Text Field, the Indicator is not showing. 

**To Reproduce**
1. Add An Indicator Item - eg for Lead Country (advanced Field, Country).
2. Set the Indicator Item to show when false or blank.
3. Add an Indicator Item Extension named USA with Contains Text = "USA".
4. Add another Indicator Item Extension named Other with Contains Text = "*".
5. On the Lead record enter the Country of USA, the Indicator displays correctly.
6. Change the Country to be blank, the Icon set on false or blank appears.
7. Now change the Country to Japan, the Indicator disappears. 

**Expected behavior**
The icon set for the Item Extension for Other should be shown

**Screenshots**
![Snag_2a0e1f32](https://github.com/SFDO-Community/Salesforce-Indicators/assets/2966583/f4a43524-32e6-43b7-9fd2-ab4a923e024c)
![Snag_2a0e2472](https://github.com/SFDO-Community/Salesforce-Indicators/assets/2966583/1377f57f-c9d8-4663-9eb5-3f923cfb2b20)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 116

**Additional context**
This org is on Hyperforce

**Comment by tschug** [comment]
I believe this is working as designed.  We are not supporting wild-card searches with `*` or `%` - so in this example, the Indicator Item should have the first column (any value) configured and not an extension to consider any value.

This new UI mocked up in the Oct-2023 Sprint would help clear up any further confusion.

**Comment by JodieM** [comment]
Closing as won't fix.
