### ISSUE TITLE
[BUG] When there is no Bundle Icon, the space is still visible

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community/Salesforce-Indicators#138]
**Describe the bug**
When I choose for the bundle to have no Icon, the space for the icon is still visible

**To Reproduce**
1. Create a Bundle and display it on the page
2. Remove the Icon Name from the Bundle configuration

**Expected behavior**
The Title is displayed left aligned within the card

**Screenshots**
![image](https://github.com/SFDO-Community/Salesforce-Indicators/assets/2966583/10fdd7fe-927d-449a-bb76-b530759862be)

See Video https://www.loom.com/share/b9d00f2a51c2469a962ac4399f296e17?sid=a0c3f4cf-e54d-4dfc-b220-4e4a8de0665a

**Desktop (please complete the following information):**
- Windows, Chrome

**Additional context**

**Comment by octatau** [comment]
@JodieM is this still an open issue? If so, I am happy to attempt a fix. I think this can be addressed by conditionally rendering the `lightning-icon` in [indicatorBundle.html](https://github.com/SFDO-Community/Salesforce-Indicators/blob/8604b3c3452249b22f4d07138da433ccf8f44a61/force-app/main/default/lwc/indicatorBundle/indicatorBundle.html#L30C29-L34C30).

**Comment by JodieM** [comment]
Hi @octatau thanks for your involvement. I think it's part of the Open feature branch that I'm testing today. And yes it should be an easy fix. Thanks.

**Comment by JodieM** [comment]
Fixed in feature/contains-equals
