### ISSUE TITLE
[BUG] If foreground Color is changed, the Icon does not render

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community/Salesforce-Indicators#142]
**Describe the bug**
When the foreground color is changed, using either HTML color names or hex color codes, the first icon only in the bundle does not render. 

**To Reproduce**
* Create a bundle with two items
* Change the foreground color of the item that displays first in the bundle
* The Icon is not visible - the background color is displayed as normal. 

**Expected behavior**
The Icon should be shown in the selected color. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Chrome
 - Version: 119

**Additional context**
NOTE: May not be a bug. More testing needed!

**Comment by tschug** [comment]
@JodieM there was a typo in the training CMDT as you lointed out, but also in the code.  So I think this is resolved if unable to replicate.

**Comment by JodieM** [comment]
Ok Closing this for now.
