### ISSUE TITLE
Contains is NOT case sensitive [BUG]

### ISSUE THREAD

**Issue by annaloughnanrad** [SFDO-Community/Salesforce-Indicators#147]
At the extension level (where I have picked it up):
using the provided option Indicator Item Extension,
Contains Text 

if you do not enter the text value as in the field, extension will not be activated.

EG
Contains Text "partner" will not display partner icon, but 
Contains Text "Partner" will display icon.

Tested against Type on Account on dev org with values such as "Technology Partner"

IMHO not necessarily an issue as long as it is made crystal clear in the documentation - I am used to searching with contains being case sensitive on some platforms but for Indicators Jodie said the intent was for it to be case insensitive! 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tschug** [comment]
Thanks for this!

We will have a fix in the works already (without realizing this bug) when we add support for other matching criteria
* Equals
* Does Not Equal
* Starts With

For interested parties - the code is here where we will be converting to lowercase and then comparing (even for Equals, based on feedback from the Oct 2023 Chicago Sprint team) :
https://github.com/SFDO-Community/Salesforce-Indicators/blob/66778d074ca4123db35cb513170632438bfb7936/force-app/main/default/lwc/indicatorBundle/indicatorBundle.js#L215-L237
