### ISSUE TITLE
[FEATURE] Match to * or ? in Extensions Contains

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community/Salesforce-Indicators#156]
**Is your feature request related to a problem? Please describe.**
When I created an Indicator Item Extension on the Contact Title field I wanted to show the same Icon if the title included
CTO
CMO
CFO
CEO
COO
CIO

I tried to enter C?O and it did not work. I tried C*O and it did not work. 
So I had to create an extension for each C-Suite position. 
Not a huge hassle as I can easily clone, but it would be useful to have wildcard characters support.

**Describe the solution you'd like**
I would like Contains to include wildcard character support.

**Comment by tschug** [comment]
We have already dismissed that Indicators isn't going to do wildcard searches like this.  Because it's a raw string logic and we have no # way of knowing if the `*` or `%` are actually part of the string or not.

**Comment by JodieM** [comment]
Yes, thanks, I just spotted that on another ticket [#130].
