### ISSUE TITLE
[BUG] Install Sample Page Layouts fails

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community/Salesforce-Indicators#163]
**Describe the bug**
Using the Install page to install the Sample Layouts causes an error. 

**To Reproduce**
1. Go to Install Page
2. Click to Install
3. Choose to Install Samples and Sample Layouts
4. An error appears during Install

**Expected behavior**
The Sample Layouts should be installed

**Screenshots**
Screen shot courtesy of Mary P on Trailblazer Community. 
<img width="936" alt="install_error" src="https://github.com/SFDO-Community/Salesforce-Indicators/assets/2966583/8af21dcb-c773-49ae-a248-780cbc35e9c2">
https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007YvbZaSAJ

**Additional context**
We had this issue during the Virtual Sprint but we thought it was a Pre-Release org issue. It seems that it is not. 

**Workaround**
The Workaround is to NOT install the Samples, and add the Bundle Component to an existing Lightning Page Layout on Account and Contact.

**Comment by kylebroeckel** [comment]
Just encountered this same error (what I'm seeing matches the above screenshot).

**Comment by tschug** [comment]
Fix for this just went through testing.  Hope to have it released this month or at the next  sprint.
