### ISSUE TITLE
Tighten up Space option

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community/Salesforce-Indicators#27]
The icons are a bit too far apart. Have an option to tighten up spacings.

**Comment by JodieM** [comment]
At this stage I changed the classes down a size. I can't see any guidelines for correct spacing in SLDS. 
Please vote if you would like to see this as an option that is set in the Config Settings. I will leave this open for now.

**Comment by tschug** [comment]
@JodieM Can we review this with the CMDT version to make sure the original issue is still an issue.

**Comment by JodieM** [comment]
Sure. The issue is sort of there still. It's moreso in smaller layouts. Maybe wait until we look at the Layout vs Card idea and the Spacer idea.

**Comment by JodieM** [comment]
I'm going to close this for now... the spacing looks OK now.
