### ISSUE TITLE
With Security Enforced

### ISSUE THREAD

**Issue by JodieM** [SFDO-Community/Salesforce-Indicators#39]
When setting up CMDT (#10) it will use an Apex Controller. Let's ensure we use all the new security trimming features of Apex to ensure that users only see the indicators for the fields they have access to. 

This one will need a bit of testing.

**Comment by tschug** [comment]
Needs to be verified with actual user acceptance testing

**Comment by tschug** [comment]
I believe this can be closed - unless someone says otherwise.  We've used the @wire's `optionalFields` to only grab the fields a user has access to.

**Comment by JodieM** [comment]
Yes, this can be closed.
